# Generated by Django 5.0.4 on 2024-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('cedula_rg', models.IntegerField()),
                ('token', models.TextField(blank=True)),
                ('curso', models.CharField(max_length=255)),
                ('fecha_evento_1', models.BooleanField(default=False)),
                ('timestamp_evento_1', models.DateTimeField(blank=True, null=True)),
                ('fecha_evento_2', models.BooleanField(default=False)),
                ('timestamp_evento_2', models.DateTimeField(blank=True, null=True)),
                ('fecha_evento_3', models.BooleanField(default=False)),
                ('timestamp_evento_3', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
