# Generated by Django 5.0.2 on 2024-04-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=200)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='cedula_rg',
            new_name='cedula',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_evento_1',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_evento_2',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_evento_3',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='timestamp_evento_1',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='timestamp_evento_2',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='timestamp_evento_3',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre_completo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llegada', models.DateTimeField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento')),
            ],
        ),
    ]
