# Generated by Django 5.0.2 on 2024-04-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0003_rename_curso_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento')),
            ],
        ),
    ]
