# Generated by Django 5.0.2 on 2024-04-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0004_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento'),
        ),
    ]
