# Generated by Django 5.0.2 on 2024-04-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0005_alumno_evento_alter_asistencia_alumno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='hora_llegada',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='evento',
        ),
        migrations.AddField(
            model_name='alumno',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
