# Generated by Django 5.0.2 on 2024-04-28 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0006_remove_asistencia_alumno_remove_asistencia_evento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='nombre_evento',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='asistencia',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='alumno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('alumnos', models.ManyToManyField(to='alumnocruds.alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.evento')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='conferencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.conferencia'),
        ),
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('alumno', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='qr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alumnocruds.qr'),
        ),
    ]
