# Generated by Django 5.0.2 on 2024-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0007_rename_nombre_evento_evento_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido',
            new_name='nombreCompleto',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumno',
            name='jornada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='talleres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.CharField(max_length=20),
        ),
    ]
