# Generated by Django 5.0.2 on 2024-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0010_alter_alumno_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
