# Generated by Django 5.0.2 on 2024-04-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0012_alumno_asistencia_hemorragia_y_fractura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='HEMORRAGIA_Y_FRACTURA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='INTUBACION_OROTRAQUEAL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='NUDO_Y_SUTURA',
            field=models.TextField(blank=True, null=True),
        ),
    ]
