# Generated by Django 5.0.2 on 2024-04-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0013_alter_alumno_hemorragia_y_fractura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='HEMORRAGIA_Y_FRACTURA',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='INTUBACION_OROTRAQUEAL',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='NUDO_Y_SUTURA',
            field=models.BooleanField(default=False),
        ),
    ]
