# Generated by Django 5.0.2 on 2024-04-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0014_alter_alumno_hemorragia_y_fractura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(max_length=20),
        ),
    ]
