# Generated by Django 5.0.2 on 2024-05-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0018_alter_alumno_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='qr',
            name='codigo',
        ),
    ]
