# Generated by Django 5.0.2 on 2024-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnocruds', '0019_remove_qr_alumno_remove_qr_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(max_length=20),
        ),
    ]
